version: '3.3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      POSTGRES_DB: odooTra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0-beta.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:admin@postgres:5432/odooTra
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      #HASURA_GRAPHQL_ADMIN_SECRET: protect
volumes:
  db_data:
